import {
  NsAffix,
  NsButton,
  NsButtonGroup,
  NsIcon,
  NsCollapse,
  NsCollapseItem,
  NsAlert,
  NsTooltip,
  NsDropdown,
  NsDropdownItem,
  NsPopconfirm,
  NsMessage,
  NsNotification,
  NsMessageBox,
  NsInput,
  NsInputNumber,
  NsLoading,
  NsSwitch,
  NsSelect,
  NsOption,
  NsForm,
  NsFormItem,
  NsTitle,
  NsText,
  NsParagraph,
  NsSpace,
  NsCheckbox,
  NsCheckboxGroup,
  NsCheckboxButton,
  NsRadio,
  NsRadioGroup,
} from '@shadow-ui/components'
import type { Plugin } from 'vue'

// Add these named exports
// export { XcButton, XcButtonGroup, XcIcon, XcCollapse, XcCollapseItem }

export default [
  NsAffix,
  NsButton,
  NsButtonGroup,
  NsIcon,
  NsCollapse,
  NsCollapseItem,
  NsAlert,
  NsTooltip,
  NsDropdown,
  NsDropdownItem,
  NsPopconfirm,
  NsMessage,
  NsNotification,
  NsMessageBox,
  NsInput,
  NsInputNumber,
  NsLoading,
  NsSwitch,
  NsSelect,
  NsOption,
  NsForm,
  NsFormItem,
  NsTitle,
  NsText,
  NsParagraph,
  NsSpace,
  NsCheckbox,
  NsCheckboxGroup,
  NsCheckboxButton,
  NsRadio,
  NsRadioGroup,
] as Plugin[]
