import {
  NsButton,
  NsButtonGroup,
  NsIcon,
  NsCollapse,
  NsCollapseItem,
  NsAlert,
  NsTooltip,
  NsDropdown,
  NsDropdownItem,
  NsPopconfirm,
  NsMessage,
  NsNotification,
  NsMessageBox,
  NsInput,
  NsLoading,
  NsSwitch,
  NsSelect,
  NsOption,
  NsForm,
  NsFormItem,
  NsTitle,
  NsText,
  NsParagraph,
  NsSpace,
} from "@shadow-ui/components";
import type { Plugin } from "vue";

// Add these named exports
// export { XcButton, XcButtonGroup, XcIcon, XcCollapse, XcCollapseItem }

export default [
  NsButton,
  NsButtonGroup,
  NsIcon,
  NsCollapse,
  NsCollapseItem,
  NsAlert,
  NsTooltip,
  NsDropdown,
  NsDropdownItem,
  NsPopconfirm,
  NsMessage,
  NsNotification,
  NsMessageBox,
  NsInput,
  NsLoading,
  NsSwitch,
  NsSelect,
  NsOption,
  NsForm,
  NsFormItem,
  NsTitle,
  NsText,
  NsParagraph,
  NsSpace,
] as Plugin[];
